### PR TITLE
Replaced ALWAYS with VERBOSE log level.

### PR DESCRIPTION
**Pull request by lcavalli**
Hi,
do you think it is a good idea to replace ALWAYS log level with VERBOSE log level?
I think that VERBOSE is more clear when logging messages.
Thanks,
Luca

### CODE REVIEW

**Comment by rdpoor** [comment]
@lcavalli : I agree that VERBOSE makes more sense than ALWAYS.  However, enough people are now using ulog that it would be better to make this a backwards compatible change, making VERBOSE and ALWAYS behave the same.  

Would you consider modifying your pull request to do that?

**Comment by lcavalli** [comment]
Something like this would fit?

**Comment by rdpoor** [comment]
Almost!  For consistancy, I'd recommend renaming `ULOG_ALWAYS` => `ULOG_ALWAYS_LEVEL`

```
  ULOG_VERBOSE_LEVEL,
  ULOG_ALWAYS=ULOG_VERBOSE_LEVEL
```

**Comment by lcavalli** [comment]
Yep, sorry.

**Pull request closed without merging**
